---
version: "3"
services:
    shinobi:
        image: shinobisystems/shinobi:dev
        container_name: Shinobi
        environment:
           - PLUGIN_KEYS={}
           - SSL_ENABLED=false
        volumes:
           - /root/Shinobi/config:/config
           - /root/Shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
           - /root/Shinobi/database:/var/lib/mysql
           - /root/Shinobi/videos:/home/Shinobi/videos
           - /root/Shinobi/plugins:/home/Shinobi/plugins
           - /dev/shm/Shinobi/streams:/dev/shm/streams
           - /etc/localtime:/etc/localtime:ro
        ports:
           - 8070:8080
        restart: unless-stopped
