---
all:
  children:
        servers:
              docker:
                    hosts:
                        docker-metal.maldonado.tech:
                testing:
                    hosts:
                        192.168.1.234:
                            ansible_ssh_user: ubuntu
        network:
            children:
                cisco:
                    hosts:
                        n3k.maldonado.tech: 
                            ansible_ssh_user: admin
                dell:
                    hosts:
                        t630.maldonado.tech:
