---
all:
    children:
        servers:
            children:  
                bsd:
                    hosts:
                        truenas.maldonado.tech:
                linux:
                    children:
                        ubuntu:
                            hosts:
                                docker-metal.maldonado.tech:
                                ansible.maldonado.tech:
                        debian:
                            hosts:    
                                pihole.maldonado.tech:
                                    ansible_ssh_user: pi
                        parrot:
                            hosts:
                                parrot.maldonado.tech:
                vmmanage:
                    hosts:
                        esxi01.maldonado.tech:
                        esxi02.maldonado.tech:
                        esxi03.maldonado.tech:
                        vcenter.maldonado.tech:
                docker:
                    hosts:
                        docker-metal.maldonado.tech:
                testing:
                    hosts:
                        192.168.1.234:
                            ansible_ssh_user: ubuntu
        network:
            children:
                cisco:
                    hosts:
                        n3k.maldonado.tech: 
                            ansible_ssh_user: admin
                dell:
                    hosts:
                        t630.maldonado.tech:
