---
all:
  children:
    servers:  
        bsd:
            truenas.maldonado.tech
        linux:
            ubuntu:
                docker.maldonado.tech
                ansible.maldonado.tech
            debian:
                pihole.maldonado.tech ansible_ssh_user=pi
            parrot:
                parrot.maldonado.tech
        vm-manage:
            esxi01.maldonado.tech
            esxi02.maldonado.tech
            esxi03.maldonado.tech
            vcenter.maldonado.tech
        docker:
            docker.maldonado.tech
        testing:
            192.168.1.166
    network:
      children:
        cisco:
            n3k.maldonado.tech ansible_ssh_user=admin
        dell:
            t630.maldonado.tech
