---
- name: get info
  hosts: n3k.maldonado.tech
  collections: cisco.nxos

  tasks:
  - name: Getting interface info
    cisco.nxos.nxos_interfaces:
      cisco.nxos.nxos_config:
      - name: Ethernet1/1
        description: Configured by Ansible      
      state: gathered
