---
- name: get info
  hosts: nxos
  collections: cisco.nxos
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.nxos.nxos
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Getting interface info
    cisco.nxos.nxos_interfaces:
      config:
        - name: Ethernet1/1
          description: Configured by Ansible
      state: merged

