---
- name: Append public key to authorized_keys
  hosts: ubuntu-server
  become: yes
  tasks:

    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Append public key to authorized_keys
      lineinfile:
        path: /home/{{ ansible_user }}/.ssh/authorized_keys
        line: "{{ lookup('file', 'files/guacamole.pub') }}"
        create: yes
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: present

