---
- name: Deploy iperf3 on target hosts
  hosts: all
  become: yes
  tasks:

    - name: Ensure package cache is updated (Debian)
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install iperf3 (Debian)
      apt:
        name: iperf3
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure iperf3 is in path
      command: which iperf3
      register: iperf3_path
      changed_when: false

    - name: Display iperf3 path
      debug:
        msg: "iperf3 installed at {{ iperf3_path.stdout }}"

