---
- name: Collect all IP addresses and output to CSV
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather network information (IP addresses)
      ansible.builtin.setup:
        gather_subset:
          - network  # Only gather network-related facts
      register: host_facts

    - name: Store IP addresses in a local file on the Ansible controller
      delegate_to: localhost
      run_once: true
      copy:
        content: |
          Hostname,IP Addresses
          {% for host in ansible_play_hosts %}
          {{ host }},
          {% if 'ansible_all_ipv4_addresses' in hostvars[host]['ansible_facts'] %}
          {{ hostvars[host]['ansible_facts']['ansible_all_ipv4_addresses'] | join(';') }}
          {% else %}
          No IPv4 address found
          {% endif %}
          {% endfor %}
        dest: /home/punchy/homelab/ip_addresses.csv
      vars:
        ansible_play_hosts: "{{ ansible_play_hosts_all }}"

