---
- name: Gather IP addresses and interface details
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather interface information
      set_fact:
        interface_data: >-
          {{ ansible_facts.interfaces | map('extract', ansible_facts) | list }}

    - name: Collect hostname, IP, and interface name
      set_fact:
        host_ip_info: >-
          {{ host_ip_info | default([]) +
          [ { 'hostname': inventory_hostname,
              'interface': item,
              'ip': ansible_facts[item]['ipv4']['address'] } ]
          if ansible_facts[item] is defined and 'ipv4' in ansible_facts[item] else host_ip_info | default([])
          }}
      loop: "{{ ansible_facts.interfaces }}"

    - name: Save result to a file on controller
      delegate_to: localhost
      run_once: true
      copy:
        dest: /tmp/ip_report.csv
        content: |
          hostname,interface,ip_address
          {% for host in ansible_play_hosts_all %}
          {% for entry in hostvars[host].get('host_ip_info', []) %}
          {{ entry.hostname }},{{ entry.interface }},{{ entry.ip }}
          {% endfor %}
          {% endfor %}

