---
- hosts: testing #using rhel9-01 
  become: true
  tasks:
  - name: install ssh pub key
    authorized_key:
      user: punchy
      state: present
      key: https://github.com/punchy98.keys
  - name: update packages
    dnf: 
      name: "*"
      state: latest
  - name: install needed programs
    dnf:
      pkg:
      - nfs-utils
      - bat 
      - vim-X11 
      - nmap
      - grubby
        #- p7zip
      - vim
  - name: remove unnecessary packages
    dnf:
      pkg:
        - nano
      state: absent
  - name: disable SELinux
    shell: grubby --update-kernel ALL --args selinux=0
  - name: update fstab
    template:
      src: /home/punchy/homelab/config-templates/fstab
      dest: /etc/fstab
  - name: mount all drives
    shell: mount -a
  - name: Install ssh key
    copy: 
      src: /home/punchy/homelab/config-templates/labkey 
      dest: /home/punchy/.ssh/labkey
      mode: 0600
      owner: punchy 
  - name: load ssh key
    shell: if [ -z "$SSH_AUTH_SOCK" ] ; then eval `ssh-agent -s` ssh-add .ssh/labkey; fi 
  - name: deploy dotfiles from git
    git:
      repo: git@github.com:punchy98/dotfiles.git
      dest: /deployment/dotfiles
      accept_hostkey: yes
      key_file: /home/punchy/.ssh/labkey
# - name: reboot
#   reboot:
#   need to add symlink mapping for configs from dotfiles
#   ln -s ~/.vimrc ~/.config/nvim/init.vim
#   ln -s ~/dotfiles/vim/.vimrc ~/.vimrc
#   ln -s ~/dotfiles/bash/.bashrc ~/.bashrc
#   ln -s ~/dotfiles/i3/config ~/.config/i3/config
#   ln -s ~/dotfiles/git/.gitconfig ~/.gitconfig
#   
