---
- hosts: testing
  become: true
  tasks:
  - name: update packages
    apt: 
      name: "*"
      state: latest
  - name: upgrade OS
    apt:
      upgrade: dist
  - name: install needed programs
    apt:
      pkg:
      - nfs-common
      - htop
      - nmap
      - mlocate
      - net-tools
  - name: disable terminal bell
    template: 
      src: /tmp/config-templates/inputrc
      dest: /etc/inputrc
  - name: Add .profile template
    template: 
      src: /tmp/config-templates/.profile
      dest: /home/punchy/.profile
  - name: Add .bash_logout
    template:
      src: /tmp/config-templates/.bash_logout
      dest: /home/punchy/.bash_logout
  - name: update fstab
    template:
      src: /tmp/fstab.config
      dest: /etc/fstab
  - name: mount all drives
    shell: mount -a
