---
- hosts: testing
  become: true
  tasks:
  - name: include vault vars
    inlude_vars: ~/homelab/ansible/vault.yml
  - name: enable EPEL 
    shell: dnf install -y --nogpgcheck https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm
  - name: enable rpm fusion
    shell: dnf install -y --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm
  - name: update packages
    dnf: 
      name: "*"
      state: latest
  - name: install needed packages
    dnf:
      pkg:
      - nfs-utils
      - neovim 
      - nmap
      - git
      - bat
      - powerline-fonts
  - name: remove unnecessary packages
    dnf:
      pkg:
        - nano
      state: absent
  - name: update fstab
    template:
      src: '{{home_dir}}'/homelab/config-templates/fstab
      dest: /etc/fstab
  - name: mount all drives
    shell: mount -a
  - name: Install ssh key
    copy: 
      src: '{{ home_dir }}'/homelab/config-templates/labkey 
      dest: '{{ home_dir }}'/.ssh/labkey
      mode: 0600
      owner: '{{ user }}' 
  - name: deploy dotfiles from git
    git:
      repo: git@github.com:punchy98/dotfiles.git
      dest: '{{ home_dir }}'/dotfiles/ 
      accept_hostkey: yes
      key_file: '{{ home_dir }}'/.ssh/labkey
  - name: remove current bashrc
    file:
      path: '{{ home_dir }}'/.bashrc
      state: absent
  - name: Create an i3 directory if it does not exist
    file:
      path: '{{ home_dir }}'/.config/i3
      state: directory
      mode: '0755'
  - name: Create an nvim directory if it does not exist
    file:
      path: '{{ home_dir }}'/.config/nvim
      state: directory
      mode: '0755'
  - name: Create a symbolic link - vimrc 
    file:
      src: '{{ home_dir }}'/dotfiles/vim/.vimrc
      dest: '{{ home_dir }}'/.vimrc 
      owner: '{{ user }}'
      state: link
  - name: Create a symbolic link - bashrc 
    file:
      src: '{{ home_dir }}'/dotfiles/bash/.bashrc
      dest: '{{ home_dir }}'/.bashrc
      owner: '{{ user }}'
      state: link
  - name: Create a symbolic link - i3 
    file:
      src: '{{ home_dir }}'/dotfiles/i3/config
      dest: '{{ home_dir }}'/.config/i3/config 
      owner: '{{ user }}'
      state: link
  - name: Create a symbolic link - git 
    file:
      src: '{{ home_dir }}'/dotfiles/git/.gitconfig
      dest: '{{ home_dir }}'/.gitconfig
      owner: '{{ user }}'
      state: link
  - name: Create a symbolic link - vimrc -> init.vim (neovim) 
    file:
      src: '{{ home_dir }}'/.vimrc
      dest: '{{ home_dir }}'/.config/nvim/init.vim 
      owner: '{{ user }}'
      state: link
# - name: reboot
#   reboot:
