---
- hosts: testing
  become: true
  tasks:
  - name: update packages
    apt: 
      name: "*"
      state: latest
  - name: upgrade OS
    apt:
      upgrade: dist
  - name: install needed programs
    apt:
      pkg:
      - nfs-common
      - htop
      - nmap
      - mlocate
      - net-tools
  - name: disable terminal bell
    template: 
      src: /tmp/config-templates/inputrc
      dest: /etc/inputrc
  - name: Add .profile template
    template: 
      src: /tmp/config-templates/.profile
      dest: /home/punchy/.profile
  - name: Add .bash_logout
    template:
      src: /tmp/config-templates/.bash_logout
      dest: /home/punchy/.bash_logout
  - name: update fstab
    template:
      src: /tmp/config-templates/fstab
      dest: /etc/fstab
  - name: mount all drives
    shell: mount -a
  - name: Install a private SSH key
    vars:
      source_key: /tmp/config-templates/labkey
      dest_key: /home/punchy/.ssh/labkey
    tasks:
    - name: Ensure .ssh directory exists.
      file: 
        dest: "{{ dest_key | dirname }}"
        mode: 0700 
        owner: punchy 
        state: directory
    - name: Install ssh key
      copy: 
        src: "{{ source_key }}" 
        dest: "{{ dest_key }}"
        mode: 0600
        owner: punchy
