---
- name: Update file permissions on plex-ubuntu
  hosts: 100.87.255.61
  become: true
  tasks:
    - name: Find all files in the transfers directory
      ansible.builtin.find:
        paths: /mnt/storage/nicotine_logs/transfers/
        file_type: file
      register: found_files

    - name: Set permissions on all found files
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: '0644'
      loop: "{{ found_files.files }}"

