version: "3"
services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    network_mode: host
    restart: ${RESTART}
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA}/torrent-blackhole:/downloads
      - ${CONFIGS}/jackett_config:/config
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: ${RESTART}
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${MEDIA}/tv:/tv
      - ${MEDIA}:/downloads
      - ${CONFIGS}/sonarr_config:/config
  
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: ${RESTART}
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${MEDIA}/movies:/tv
      - ${MEDIA}:/downloads
      - ${CONFIGS}/radarr_config:/config
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: ${RESTART}
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${MEDIA}/movies:/movies
      - ${MEDIA}/tv:/tv
      - ${CONFIGS}/bazarr_config:/config
  kuma:
    container_name: kuma
    image: louislam/uptime-kuma:1
    restart: ${RESTART}
    ports:
      - 3001:3001
    volumes:
      - ${CONFIGS}/kuma_config:/app/data
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIGS}/tautulli_config:/config
    ports:
      - 8282:8181
    restart: ${RESTART}
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${CONFIGS}/overseerr_config:/app/config
    restart: ${RESTART}
#  sabnzbd:
#    image: lscr.io/linuxserver/sabnzbd:latest
#    container_name: sabnzbd
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=${TIMEZONE}
#    volumes:
#      - ${CONFIGS}/sabnzbd_configs:/config
#      - ${MEDIA}/downloads:/downloads
#      - ${MEDIA}/incomplete-downloads:/incomplete-downloads
#    ports:
#      - 8383:8080
#    restart: ${RESTART}
