---
- hosts: testing
  become: true
  tasks:
  - name: update packages
    apt: 
      name: "*"
      state: latest
  - name: upgrade OS
    apt:
      upgrade: dist
  - name: install needed programs
    apt:
      pkg:
      - nfs-common
      - htop
      - nmap
      - mlocate
      - net-tools
  - name: disable terminal bell
    template: 
      src: /tmp/config-templates/inputrc
      dest: /etc/inputrc
  - name: Add .profile template
    template: 
      src: /tmp/config-templates/.profile
      dest: /home/ubuntu/.profile
  - name: Add .bash_logout
    template:
      src: /tmp/config-templates/.bash_logout
      dest: /home/ubuntu/.bash_logout
  - name: Update .bashrc
    template:
      src: /tmp/config-templates/.bashrc
      dest: /home/ubuntu/.bashrc
  - name: Update nanorc
    template:
      src: /tmp/config-templates/nanorc
      dest: /etc/nanorc
  - name: update fstab
    template:
      src: /tmp/config-templates/fstab
      dest: /etc/fstab
  - name: mount all drives
    shell: mount -a
  - name: Install ssh key
    copy: 
      src: /tmp/config-templates/labkey 
      dest: /home/ubuntu/.ssh/labkey
      mode: 0600
      owner: ubuntu
