---
- hosts: servers
  become: true
  tasks:
  - name: update packages
    apt: 
      name: "*"
      state: latest
  - name: upgrade OS
    apt:
      upgrade: dist
  - name: disable terminal bell
    template: 
      src: /tmp/config-templates/inputrc
      dest: /etc/inputrc
  - name: install needed programs
    apt:
      pkg:
      - nfs-common
      - htop
      - nmap
      - mlocate
  - name: update fstab
    template:
      src: /tmp/fstab
      dest: /etc/fstab
  - name: mount all drives
    shell: mount -a
